### ISSUE TITLE
Cannot cast me.itsario.ZombieSMP to com.ericdebouwer.zombieapocalypse.ZombieApocalypse

### ISSUE THREAD

**Issue by Its-Ario** [EricLangezaal/ZombieApocalypse#12]
Hi, Im Working On An Add-On. When I Build The Plugin And Start The Server, I Get This Error:

[13:31:12] [Server thread/ERROR]: Error occurred while enabling ZombieSMP v0.1-SNAPSHOT (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at me.itsario.ZombieSMP.onEnable(ZombieSMP.java:14) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:539) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3635-Spigot-d90018e-941d7e9]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:453) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3635-Spigot-d90018e-941d7e9]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:587) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3635-Spigot-d90018e-941d7e9]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:412) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3635-Spigot-d90018e-941d7e9]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3635-Spigot-d90018e-941d7e9]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3635-Spigot-d90018e-941d7e9]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:301) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3635-Spigot-d90018e-941d7e9]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassCastException: Cannot cast me.itsario.ZombieSMP to com.ericdebouwer.zombieapocalypse.ZombieApocalypse
        at java.lang.Class.cast(Class.java:3889) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.getPlugin(JavaPlugin.java:404) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at com.ericdebouwer.zombieapocalypse.api.ApocalypseAPI.<init>(ApocalypseAPI.java:22) ~[?:?]
        at com.ericdebouwer.zombieapocalypse.api.ApocalypseAPI.<clinit>(ApocalypseAPI.java:18) ~[?:?]
        ... 12 more

**Comment by EricLangezaal** [comment]
The problem seems to be that you are attempting to cast plugin classes (I think). Could you please share the relevant code?

**Comment by Its-Ario** [comment]
[Zombies.zip](https://github.com/EricLangezaal/ZombieApocalypse/files/10360763/Zombies.zip)
Project Code

**Comment by EricLangezaal** [comment]
You seem to be (unintentionally) shading in my plugin for some reason? That of course doesn't work, it is not a framework or library of sorts, but a plugin of its own which should be added to the plugins folder like a regular plugin. Otherwise you will get weird conflicts like this.

**Comment by Its-Ario** [comment]
I'm new to java. This is my first plugin using developer API. What should I do now?

I Just Followed The Instructions Told In The Wiki

**Comment by EricLangezaal** [comment]
Well you shouldn't shade my plugin. So either remove the Maven shade plugin from your pom.xml, or mark my plugin's dependency as `<scope>provided</scope>` like you do for the Spigot core. (And then just put the ZombieApocalypse plugin on the server you are developing on, and on any servers where you wish to use your own plugin since it depends on it now)

**Comment by Its-Ario** [comment]
Thanks. It Got Fixed
